# The URL the site will be built for
base_url = "https://lukazmm.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Default Language is English
default_language = "en"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "docs"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` files.
extra_syntaxes = []

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "one-dark"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = false


# [extra]
# # Put all your custom variables here

# # Site settings
# description = "Personal Site of Lukas Mesicek"

# # User settings
# user_name = "Lukas Mesicek"
# user_title = "Student Researcher at the University of Utah"

# # Socials
# email = "lukas.m.mesicek@gmail.com"
# github = "lukazmm"

# Enable external libraries
[extra]
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/publications", name = "Publications" },
        { url = "$BASE_URL/cv/MesicekCV.pdf", name = "CV", new = true },
        # { url = "$BASE_URL/tags", name = "Tags" },
        # { url = "$BASE_URL/categories", name = "Categories" },
    ] },
]

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/favicon/favicon-16x16.png"
favicon_32x32 = "/favicon/favicon-32x32.png"
apple_touch_icon = "/favicon/apple-touch-icon.png"
safari_pinned_tab = "/favicon/safari-pinned-tab.svg"
webmanifest = "/favicon/site.webmanifest"

# Author details
[extra.author]
name = "Lukas Mesicek"
avatar = "/img/profile.png"

# Social links
[extra.social]
email = "lukas.m.mesicek@gmail.com"
# facebook = "<facebook_username>"
github = "lukazmm"
# gitlab = "<gitlab_username>"
# keybase = "<keybase_username>"
linkedin = "lukas-mesicek-833a30256"
# stackoverflow = "<stackoverflow_userid>"
# twitter = "<twitter_username>"
# instagram = "<instagram_username>"
# behance = "<behance_username>"
# google_scholar = "<googlescholar_userid>"
orcid = "0009-0002-3259-1282"
# mastodon_username = "<mastadon_username>"
# mastodon_server = "<mastodon_server>"


# To add google analytics
# [extra.analytics]
# google = "<your_gtag>"

# To add disqus comments
# [extra.commenting]
# disqus = "<your_disqus_shortname>"

# To enable mapbox maps
[extra.mapbox]
enabled = false
# access_token = "<your_access_token>"
